# Examen A Módulo 1 - Optimización.

**Lea cuidadosamente las siguientes indicaciones antes de comenzar el examen:**
- Para resolver el examen edite este mismo archivo y renómbrelo de la siguiente manera: *Examen1_ApellidoNombre*, donde *ApellidoNombre* corresponde a su apellido paterno con la inicial en mayúscula, seguido de su primer nombre con la inicial en mayúscula **sin tildes**. Por ejemplo, en mi caso el nombre del archivo sería *Examen1_MoralesGabriel*.
- Resuelva los puntos en el espacio provisto. Si requiere agregar más celdas para código o escritura, hágalo (`Esc`,`B`) o (`Esc`,`A`).
- Recuerde que también se está evaluando su capacidad de interpretar los resultados. Escriba sus interpretaciones/conclusiones en celdas utilizando *Markdown*.
- El formato de presentación de todo el examen en general debe ser adecuado. Use tamaños de letra, colores, etiquetas, etcétera.
- No se resuelven dudas de ningún tipo por los profesores de la asignatura. Por favor, absténgase de preguntar.
- Revise bien el tipo de examen. Sólo se le calificará si realiza el tipo de examen asignado.

# Mariano Villanueva Aguilar

## 1. Optimización de funciones con `Sympy`

Funciones permitidas: subs, solve, var, expresiones matemáticas


Un cine cobra 86 pesos la entrada estándar y 60 pesos la entrada a estudiantes. Una sala con capacidad para 120 personas se ocupó al 70\%. Los ingresos para esa función fueron de 6,600 MXN. ¿Cuántos estudiantes entraron?

86 pesos la entrada estandar (x) y 60 la de estudiantes (y)

$$ 6600=86x+60y$$

In [9]:
Personas=0.7*120
Personas

84.0

$$ 84=x+y $$

In [11]:
import sympy as sp
sp.var("x")
sp.var("y")
Dinero=86*x+60*y-6600
Publico=x+y-84
x_y=sp.solve(Publico,x)[0]
Ry=sp.solve(Dinero.subs(x,x_y),y)
Ry

[24]

El cine ofrece combos y opciones individuales. El combo 'amigos' tiene un costo de 156 MXN y consiste de 2 refrescos y unas palomitas. Existe también el combo 'nachos' que tiene un costo de 112 MXN y consiste de un refresco y una orden de nachos. Por separado el refresco tiene un costo de 60 MXN, las palomitas 58 MXN y los nachos 72 MXN. Se obtuvo un total de 6450 de ingresos en dulcería:

- 38 combos vendidos
- 70 refrescos vendidos
- 33 órdenes de palomitas grandes vendidas
- 16 órdenes de nachos vendidas

¿Cuántas personas compraron palomitas sueltas?

In [13]:
sp.var("ca")
sp.var("cn")
sp.var("r")
sp.var("p")
sp.var("n")
Total=156*ca+112*cn+60*r+58*p+72*n-6450
Combos=ca+cn-38
Refrescos=2*ca+r+cn-70
Palomitas=p+ca-33
Nachos=cn+n-16
combos_ca=sp.solve(Combos,cn)[0]
Refrescos_ca=sp.solve((Refrescos.subs(cn,combos_ca)),r)[0]
Palomitas_ca=sp.solve(Palomitas,p)[0]
Nachos_ca=sp.solve((Nachos.subs(cn,combos_ca)),n)[0]
Total=Total.subs(cn,combos_ca)
Total=Total.subs(r,Refrescos_ca)
Total=Total.subs(p,Palomitas_ca)
Total=Total.subs(n,Nachos_ca)
Total=sp.solve(Total,ca)[0]
TotalPalomitasSueltas=Palomitas_ca.subs(ca,Total)
TotalPalomitasSueltas

5

## 2. Programación lineal

Una empresa produce costales de 3 tipos de fertilizantes para diferentes aplicaciones utilizando cuantro componentes químicos: azufre, potasio, fósforo y nitrógeno. La información de cada tonelada de fertilizante es:


<table>
  <tr>
      <th>Fertilizante</th>
      <th>Fósforo</th>
      <th>Azufre</th>
      <th>Potasio</th>
      <th>Nitrógeno</th>
      <th>Precio de venta </th>
  </tr>
  <tr>
      <td>A</td>
      <td>3 kg</td>
      <td>5 kg</td>
      <td>4 kg</td>
      <td>2 kg </td>
      <td>\$40000</td>
  </tr>
  <tr>
      <td>B</td>
      <td>4 kg</td>
      <td>3 kg</td>
      <td>2 kg</td>
      <td>1 kg</td>
      <td>\$50000</td>
  </tr>
  <tr>
      <td>C</td>
      <td>5 kg</td>
      <td>2 kg</td>
      <td>3 kg</td>
      <td>4 kg</td>
      <td>\$60000</td>
  </tr>

</table>

La máquina que se usa para mezclar el fertilizante C necesita mantenimiento y por lo tanto sólo puede mezclar 10 toneladas. Además, hay un pedido de 8 toneladas del fertilizante A.

Dado que en almacén se tienen 90 kg de fósforo, 120 kg de nitrógeno, 80 kg de azufre y 95 kg de potasio, ¿cuánto recomiendas que se mezcle de cada fertilizante? (Nota: No se permiten fracciones de toneladas)

Maximizar la ganancia

$$ Ganancia=40000A+50000B+60000C$$

Fósforo
$$3A+4B+5C \leq 90 $$
Azufre
$$ 5A+3B+2C \leq 80 $$
Potasio
$$ 4A+2B+3C \leq 95 $$
Nitrógeno
$$ 2A+3B+2C \leq 80 $$

Fertilizante C
$$ C\leq 10 $$

Fertilizante A
$$ A\geq 8 $$

In [136]:
import numpy as np
import scipy.optimize as opt
c=np.array([-40000,-50000,-60000])
Aub=np.array([
    [3,4,5],
    [5,3,2],
    [4,2,3],
    [2,3,2],
    [0,0,1],
    [-1,0,0],
])
bub=np.array([
    [90],
    [80],
    [95],
    [80],
    [10],
    [-8]
])
sol=opt.linprog(c,Aub,bub, integrality=1)
sol

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -1130000.0
              x: [ 8.000e+00  9.000e+00  6.000e+00]
            nit: -1
          lower:  residual: [ 8.000e+00  9.000e+00  6.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00  2.700e+01  2.500e+01
                              4.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: -1130000.0
        mip_gap: 0.0

¿Cuál es el ingreso total?

In [142]:
-1*sol.fun

1130000.0

¿Cuánto fósforo quedó en almacén?

In [147]:
Fosfororestante=90-sol.x[0]-sol.x[1]
Fosfororestante

73.0

## 3. Regresión lineal

Se quiere predecir la resistencia a la compresión de concreto en función de las proporciones de los componentes en la mezcla (cemento, arena, agua, agregado). La constructora que está realizando el análisis tiene datos históricos donde se registraron cantidades de materia y la resistencia medida:

In [31]:
import pandas as pd
data = {
    'Cemento (kg)': [350, 400, 300, 450, 380, 410, 320, 370, 390, 360, 
                     340, 430, 315, 405, 425, 345, 395, 355, 440, 310, 
                     385, 370, 425, 335],
    'Arena (kg)': [600, 550, 700, 500, 580, 540, 650, 590, 570, 610, 
                   630, 520, 660, 545, 530, 620, 560, 605, 515, 670, 
                   575, 590, 535, 625],
    'Agua (kg)': [180, 160, 200, 170, 175, 165, 185, 172, 170, 190, 
                  182, 165, 195, 175, 168, 180, 175, 185, 162, 198, 
                  178, 172, 170, 180],
    'Agregado (kg)': [1000, 1100, 950, 1200, 1050, 1150, 980, 1020, 1080, 970, 
                      990, 1120, 950, 1060, 1140, 990, 1040, 1010, 1160, 940, 
                      1070, 1030, 1110, 1025],
    'Resistencia a la compresión (MPa)': [35, 42, 30, 50, 38, 44, 32, 36, 40, 34, 
                                          33, 48, 31, 43, 47, 37, 41, 35, 49, 29, 
                                          39, 36, 45, 33]
}
data = pd.DataFrame(data)
data

Cemento (kg)  Arena (kg)  Agua (kg)  Agregado (kg)  \
0            350         600        180           1000   
1            400         550        160           1100   
2            300         700        200            950   
3            450         500        170           1200   
4            380         580        175           1050   
5            410         540        165           1150   
6            320         650        185            980   
7            370         590        172           1020   
8            390         570        170           1080   
9            360         610        190            970   
10           340         630        182            990   
11           430         520        165           1120   
12           315         660        195            950   
13           405         545        175           1060   
14           425         530        168           1140   
15           345         620        180            990   
16           395         560        175           1040   
17           355         605        185           1010   
18           440         515        162           1160   
19           310         670        198            940   
20           385         575        178           1070   
21           370         590        172           1030   
22           425         535        170           1110   
23           335         625        180           1025   

    Resistencia a la compresión (MPa)  
0                                  35  
1                                  42  
2                                  30  
3                                  50  
4                                  38  
5                                  44  
6                                  32  
7                                  36  
8                                  40  
9                                  34  
10                                 33  
11                                 48  
12                                 31  
13                                 43  
14                                 47  
15                                 37  
16                                 41  
17                                 35  
18                                 49  
19                                 29  
20                                 39  
21                                 36  
22                                 45  
23                                 33

Ajusta un modelo utilizando mínimos cuadrados para encontrar una función que pueda predecir la resistencia del concreto.

In [33]:
import numpy as np
import scipy.optimize as opt
x1=data["Cemento (kg)"]
x2=data["Arena (kg)"]
x3=data["Agua (kg)"]
x4=data["Agregado (kg)"]
y=data["Resistencia a la compresión (MPa)"]
n=len(y)
ones=np.ones([n,1])
factor_x1=np.reshape(x1,[n,1])
factor_x2=np.reshape(x2,[n,1])
factor_x3=np.reshape(x3,[n,1])
factor_x4=np.reshape(x4,[n,1])
X=np.hstack((ones,factor_x1,factor_x2,factor_x3,factor_x4))
y_vector=np.reshape(y,[n,1])
n,p=X.shape
beta=np.random.rand(p)
def F(beta,X,y):
    beta=np.reshape(beta,[p,1])
    y_pred=X@beta
    error=y_pred-y
    rss=error.T@error
    return rss[0,0]
B=opt.minimize(F,beta,args=(X,y_vector))
B

  message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: 29.849890303582235
        x: [-5.577e+01  1.374e-01  2.437e-02  1.946e-02  2.397e-02]
      nit: 20
      jac: [ 1.979e-03  7.520e-01  1.163e+00  3.335e-01  2.078e+00]
 hess_inv: [[ 4.499e+02 -5.332e-01 ...  1.577e-01 -2.731e-03]
            [-5.332e-01  8.616e-04 ... -4.419e-04 -9.367e-05]
            ...
            [ 1.577e-01 -4.419e-04 ...  1.153e-03  7.713e-05]
            [-2.731e-03 -9.367e-05 ...  7.713e-05  4.279e-05]]
     nfev: 348
     njev: 56

¿Qué efecto tiene cada factor en la resistencia de la mezcla?

In [35]:
B.x

array([-5.57675735e+01,  1.37393414e-01,  2.43727156e-02,  1.94596214e-02,
        2.39716987e-02])

Por cada kilogramo de cemento, afecta 1.37379167e-01 veces, por cada de Arena  2.43593758e-02, por cada de agua  1.94843394e-02 y por cada de agregado 2.39738515e-02

¿Cuál será la resistencia si mezclo 390 kg de cemento, 570 kg de arena, 170 kg de agua y 1080 kg de agregado?

In [38]:
Resistencia=-5.57610828e+01 + 1.37379167e-01*390+2.43593758e-02*570+1.94843394e-02*170+2.39738515e-02*1080
Resistencia

40.905733854000005

## 4. Regresión logística

Un equipo de ingenieros quiere saber si una muestra de concreto hidráulico fallará o no bajo determinadas condiciones, basándose en experiencias pasadas.

<table>
  <thead>
    <tr>
      <th>Resistencia a la compresión (MPa)</th>
      <th>Edad del concreto (días)</th>
      <th>Relación agua-cemento</th>
      <th>Falla (Sí/No)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>25</td>
      <td>28</td>
      <td>0.45</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>40</td>
      <td>56</td>
      <td>0.35</td>
      <td>No</td>
    </tr>
    <tr>
      <td>30</td>
      <td>28</td>
      <td>0.50</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>50</td>
      <td>90</td>
      <td>0.30</td>
      <td>No</td>
    </tr>
    <tr>
      <td>35</td>
      <td>28</td>
      <td>0.40</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>55</td>
      <td>120</td>
      <td>0.32</td>
      <td>No</td>
    </tr>
    <tr>
      <td>45</td>
      <td>60</td>
      <td>0.36</td>
      <td>No</td>
    </tr>
    <tr>
      <td>20</td>
      <td>7</td>
      <td>0.55</td>
      <td>Sí</td>
    </tr>
  </tbody>
</table>


1. ¿Qué factor afecta más? (Utiliza un vector de ceros como tu beta inicial)

In [42]:
MPa=np.array([[25],[40],[30],[50],[35],[55],[45],[20]])
Edad=np.array([[28],[56],[28],[90],[28],[120],[60],[7]])
Relacion=np.array([[0.45],[0.35],[0.50],[0.30],[0.40],[0.32],[0.36],[0.55]])
Falla=np.array([[1],[0],[1],[0],[1],[0],[0],[1]])

In [43]:
Y=Falla

In [44]:
N=len(Y)
Ones=np.ones([N,1])
XX=np.hstack((Ones,MPa,Edad,Relacion))
Y_vector=np.reshape(Y,[N,1])
XX

array([[  1.  ,  25.  ,  28.  ,   0.45],
       [  1.  ,  40.  ,  56.  ,   0.35],
       [  1.  ,  30.  ,  28.  ,   0.5 ],
       [  1.  ,  50.  ,  90.  ,   0.3 ],
       [  1.  ,  35.  ,  28.  ,   0.4 ],
       [  1.  ,  55.  , 120.  ,   0.32],
       [  1.  ,  45.  ,  60.  ,   0.36],
       [  1.  ,  20.  ,   7.  ,   0.55]])

In [87]:
def P(Beta,XX):
    return(1/(1+np.exp(-XX@Beta)))

def J(Beta,XX,Y):
    epsilon=1e-45
    n,p=XX.shape
    Beta=np.reshape(Beta,[p,1])
    Y_pred=P(Beta,XX)
    e=Y*np.log(Y_pred+epsilon)+(1-Y)*np.log(1-Y_pred+epsilon)
    return -np.sum(e)

BETA=np.array([0, 0, 0, 0])
RL=opt.minimize(J,BETA,args=(XX,Y_vector))
RL

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.1236079788292108e-07
        x: [ 2.223e+01  2.043e+00 -2.254e+00  1.432e+01]
      nit: 28
      jac: [ 9.686e-08  5.215e-06  7.354e-06  4.470e-08]
 hess_inv: [[ 3.268e+06  2.756e+05 -3.119e+05  2.104e+06]
            [ 2.756e+05  2.324e+04 -2.630e+04  1.775e+05]
            [-3.119e+05 -2.630e+04  2.977e+04 -2.009e+05]
            [ 2.104e+06  1.775e+05 -2.009e+05  1.355e+06]]
     nfev: 155
     njev: 31

2. Calcula la probabilidad de falla para una muestra con las siguientes características:
- Resistencia a la compresión: 38 MPa
- Edad del concreto: 30 días
- Relación agua-cemento: 0.40

In [125]:
prueba=np.array([1,38,30,0.40])

In [127]:
P(prueba,RL.x)

1.0

100% de probabilidad